<?php

declare(strict_types=1);

require_once __DIR__ . '/AtomicFile.php';
require_once __DIR__ . '/BuildLock.php';

final class JavaScriptBuilder
{
    public const VERSION = '0.28.2';

    public static function binary(string $root): string
    {
        return $root . '/storage/tools/esbuild-' . self::VERSION . (PHP_OS_FAMILY === 'Windows' ? '.exe' : '');
    }

    public static function build(string $root): void
    {
        BuildLock::acquire($root);
        $binary = self::binary($root);
        if (!is_file($binary)) throw new RuntimeException('Install esbuild first: composer js:install');
        $metadata = tempnam(sys_get_temp_dir(), 'lolissr-js-');
        if ($metadata === false) throw new RuntimeException('Cannot create build metadata file');
        try
        {
            $process = proc_open([
                $binary, 'public/js/app.js', '--bundle', '--splitting', '--format=esm',
                '--platform=browser', '--target=es2022', '--minify', '--charset=utf8',
                '--outdir=public/js/dist', '--entry-names=[name]-[hash]', '--chunk-names=chunks/[name]-[hash]',
                '--metafile=' . $metadata, '--log-level=warning',
            ], [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR], $pipes, $root, null, ['bypass_shell' => true]);
            if (!is_resource($process)) throw new RuntimeException('Cannot start esbuild');
            fclose($pipes[0]);
            if (proc_close($process) !== 0) throw new RuntimeException('JavaScript build failed');
            $data = json_decode((string)file_get_contents($metadata), true, 512, JSON_THROW_ON_ERROR);
            $entry = null;
            foreach ($data['outputs'] as $path => $output)
            {
                if (($output['entryPoint'] ?? '') === 'public/js/app.js') $entry = $path;
                foreach ($output['imports'] as $import)
                {
                    if ($import['external'] ?? false) throw new RuntimeException('Unbundled import: ' . $import['path']);
                }
            }
            if ($entry === null) throw new RuntimeException('Missing JavaScript entry');
            $preloads = [];
            $visit = static function (string $path) use (&$visit, &$preloads, $data): void {
                foreach ($data['outputs'][$path]['imports'] as $import)
                {
                    if ($import['kind'] !== 'import-statement' || isset($preloads[$import['path']])) continue;
                    $preloads[$import['path']] = true;
                    $visit($import['path']);
                }
            };
            $visit($entry);
            $manifest = [
                'entry' => substr($entry, strlen('public/')),
                'preloads' => array_map(static fn (string $path): string => substr($path, strlen('public/')), array_keys($preloads)),
                'files' => array_map(static fn (string $path): string => substr($path, strlen('public/')), array_keys($data['outputs'])),
            ];
            $php = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by scripts/Assets/build-js.php.\nreturn " . var_export($manifest, true) . ";\n";
            $sources = [
                'manifest_hash' => hash('sha256', serialize($manifest)),
                'sources' => array_combine(array_keys($data['inputs']), array_map(
                    static fn (string $path): string => (string)hash_file('sha256', $root . '/' . $path), array_keys($data['inputs'])
                )),
            ];
            AtomicFile::writeIfChanged($root . '/scripts/Assets/javascript-sources.php',
                "<?php\n\ndeclare(strict_types=1);\n\n// Generated by scripts/Assets/build-js.php; build verification only.\nreturn "
                . var_export($sources, true) . ";\n");
            AtomicFile::writeIfChanged($root . '/Config/javascript.php', $php);
            $bytes = $data['outputs'][$entry]['bytes'];
            foreach (array_keys($preloads) as $path) $bytes += $data['outputs'][$path]['bytes'];
            echo 'JavaScript startup: ' . (1 + count($preloads)) . ' files, ' . $bytes . " bytes\n";
        }
        finally
        {
            if (is_file($metadata)) unlink($metadata);
        }
    }
}
