<?php

declare(strict_types=1);

require __DIR__ . '/build-css.php';

$assetRoot = dirname(__DIR__) . '/public/';
$assetVersions = [];
foreach (['css', 'js'] as $assetDirectory)
{
    $assetFiles = new RecursiveIteratorIterator(new RecursiveDirectoryIterator(
        $assetRoot . $assetDirectory, FilesystemIterator::SKIP_DOTS
    ));
    foreach ($assetFiles as $assetFile)
    {
        if (! $assetFile->isFile() || ! in_array($assetFile->getExtension(), ['css', 'js'], true)) continue;
        $assetPath = str_replace('\\', '/', substr($assetFile->getPathname(), strlen($assetRoot)));
        $assetHash = hash_file('sha256', $assetFile->getPathname());
        if ($assetHash === false) throw new RuntimeException('Cannot hash asset: ' . $assetPath);
        $assetVersions[$assetPath] = $assetHash;
    }
}
ksort($assetVersions);
$assetManifest = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by scripts/build-assets.php.\nreturn "
    . var_export($assetVersions, true) . ";\n";
$assetManifestPath = dirname(__DIR__) . '/Config/assets.php';
if (! is_file($assetManifestPath) || file_get_contents($assetManifestPath) !== $assetManifest)
{
    if (file_put_contents($assetManifestPath, $assetManifest, LOCK_EX) === false)
    {
        throw new RuntimeException('Cannot write asset manifest.');
    }
}
echo 'Asset versions: ' . count($assetVersions) . PHP_EOL;
