<?php

declare(strict_types=1);

require_once __DIR__ . '/../lib/BuildLock.php';
BuildLock::acquire(dirname(__DIR__, 2));
require __DIR__ . '/build-css.php';
require __DIR__ . '/build-js.php';

$assetRoot = dirname(__DIR__, 2) . '/public/';
$assetVersions = [];
foreach (['css', 'js'] as $assetDirectory)
{
    $assetFiles = new RecursiveIteratorIterator(new RecursiveDirectoryIterator(
        $assetRoot . $assetDirectory, FilesystemIterator::SKIP_DOTS
    ));
    foreach ($assetFiles as $assetFile)
    {
        if (! $assetFile->isFile() || ! in_array($assetFile->getExtension(), ['css', 'js'], true)) continue;
        $assetPath = str_replace('\\', '/', substr($assetFile->getPathname(), strlen($assetRoot)));
        $assetHash = hash_file('sha256', $assetFile->getPathname());
        if ($assetHash === false) throw new RuntimeException('Cannot hash asset: ' . $assetPath);
        $assetVersions[$assetPath] = $assetHash;
    }
}
ksort($assetVersions);
$assetManifest = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by scripts/Assets/build-assets.php.\nreturn "
    . var_export($assetVersions, true) . ";\n";
$assetManifestPath = dirname(__DIR__, 2) . '/Config/assets.php';
AtomicFile::writeIfChanged($assetManifestPath, $assetManifest);
echo 'Asset versions: ' . count($assetVersions) . PHP_EOL;
