<?php

declare(strict_types=1);

require_once __DIR__ . '/../../Support/AtomicFile.php';
require_once __DIR__ . '/../../Assets/JavaScript/Support/JavaScriptBuilder.php';

final class DxFormatter
{
    private array $config;
    private string $root;

    public function __construct(string $root, string $configPath)
    {
        $resolved = realpath($root);
        if ($resolved === false) throw new InvalidArgumentException('Racine DX introuvable.');
        $this->root = str_replace('\\', '/', $resolved);
        $json = file_get_contents($configPath);
        if ($json === false) throw new InvalidArgumentException('Configuration DX introuvable.');
        $config = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        if (!is_array($config)) throw new InvalidArgumentException('La configuration DX doit etre un objet JSON.');
        foreach (['paths', 'extensions', 'exclude'] as $key)
        {
            if (!isset($config[$key]) || !is_array($config[$key]) || !array_is_list($config[$key]))
                throw new InvalidArgumentException('Liste DX invalide : ' . $key);
            foreach ($config[$key] as $value)
            {
                if (!is_string($value) || $value === '') throw new InvalidArgumentException('Valeur DX invalide : ' . $key);
            }
        }
        if (!isset($config['line_length']) || !is_int($config['line_length']) || $config['line_length'] < 40)
            throw new InvalidArgumentException('line_length doit etre un entier >= 40.');
        if (array_diff($config['extensions'], ['php', 'js', 'css']) !== [])
            throw new InvalidArgumentException('Extensions DX autorisees : php, js, css.');
        $this->config = $config;
    }

    // =================================================
    // EXÉCUTION
    // =================================================

    public function run(bool $check): int
    {
        $pending = [];
        $files = $this->files();
        foreach ($files as $path)
        {
            $original = file_get_contents($path);
            if ($original === false) throw new RuntimeException('Lecture impossible : ' . $path);
            if (preg_match('/^\/\/ Generated by /m', $original)) continue;
            $extension = pathinfo($path, PATHINFO_EXTENSION);
            $formatted = $this->format($original, $extension);
            if ($formatted === $original) continue;
            $pending[$path] = [$original, $formatted];
            echo ($check ? 'CHECK ' : 'DX ') . substr($path, strlen($this->root) + 1) . PHP_EOL;
        }

        // Toutes les transformations sont validees avant la premiere ecriture.
        if (!$check)
        {
            foreach ($pending as $path => [$original, $formatted])
            {
                if (file_get_contents($path) !== $original)
                    throw new RuntimeException('Fichier modifie pendant le formatage : ' . $path);
                AtomicFile::writeIfChanged($path, $formatted);
            }
        }

        echo count($files) . ' sources analysees, ' . count($pending)
            . ($check ? ' a reformater.' : ' reformatees.') . PHP_EOL;
        if (!$check && $pending !== []) echo "Pour actualiser les assets : composer assets:build\n";
        return $check && $pending !== [] ? 1 : 0;
    }

    public function format(string $source, string $extension): string
    {
        $newline = str_contains($source, "\r\n") ? "\r\n" : "\n";
        // Les litteraux et les fins de ligne existantes restent intacts.
        $formatted = match ($extension)
        {
            'php' => $this->formatPhp($source, $newline),
            'js' => $this->formatJs($source, $newline),
            'css' => $this->formatCss($source),
            default => throw new InvalidArgumentException('Extension DX inconnue : ' . $extension)
        };
        if ($extension === 'php')
        {
            if ($this->phpSignature($source) !== $this->phpSignature($formatted))
                throw new RuntimeException('Transformation PHP refusee : instructions ou litteraux modifies.');
        }
        elseif ($formatted !== $source && $this->compile($source, $extension) !== $this->compile($formatted, $extension))
        {
            throw new RuntimeException('Transformation ' . $extension . ' refusee : compilation differente.');
        }
        return $formatted;
    }

    // =================================================
    // SÉLECTION DES SOURCES
    // =================================================

    private function files(): array
    {
        $files = [];
        foreach ($this->config['paths'] as $relative)
        {
            if (preg_match('~^(?:[A-Za-z]:|[/\\\\])|(?:^|[/\\\\])\.\.(?:[/\\\\]|$)~', $relative))
                throw new InvalidArgumentException('Chemin DX hors projet : ' . $relative);
            $path = realpath($this->root . '/' . $relative);
            if ($path === false) throw new InvalidArgumentException('Chemin DX introuvable : ' . $relative);
            $path = str_replace('\\', '/', $path);
            $this->assertInsideRoot($path);
            if (is_file($path))
            {
                $candidates = [$path];
            }
            else
            {
                $iterator = new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS);
                $filter = new RecursiveCallbackFilterIterator($iterator, function ($file): bool
                {
                    if ($file->isLink()) return false;
                    return !$this->excluded(str_replace('\\', '/', $file->getPathname()));
                });
                $candidates = [];
                foreach (new RecursiveIteratorIterator($filter) as $file)
                {
                    if ($file->isFile()) $candidates[] = str_replace('\\', '/', $file->getPathname());
                }
            }
            foreach ($candidates as $candidate)
            {
                $this->assertInsideRoot($candidate);
                if (!$this->excluded($candidate) && in_array(pathinfo($candidate, PATHINFO_EXTENSION), $this->config['extensions'], true))
                    $files[$candidate] = true;
            }
        }
        $paths = array_keys($files);
        sort($paths, SORT_STRING);
        return $paths;
    }

    private function assertInsideRoot(string $path): void
    {
        $candidate = $path . '/';
        $root = $this->root . '/';
        if (PHP_OS_FAMILY === 'Windows')
        {
            $candidate = strtolower($candidate);
            $root = strtolower($root);
        }
        if (!str_starts_with($candidate, $root))
            throw new InvalidArgumentException('Chemin DX hors projet : ' . $path);
    }

    private function excluded(string $path): bool
    {
        $relative = substr($path, strlen($this->root) + 1);
        foreach (['vendor/', 'node_modules/', '.git/', 'storage/', 'releases/', 'public/js/dist/', ...$this->config['exclude']] as $excluded)
        {
            if (str_ends_with($excluded, '/'))
            {
                if (str_starts_with($relative . '/', $excluded)) return true;
            }
            elseif ($relative === $excluded)
            {
                return true;
            }
        }
        return false;
    }

    // =================================================
    // PHP
    // =================================================

    private function formatPhp(string $source, string $newline): string
    {
        $originalTokens = token_get_all($source, TOKEN_PARSE);
        foreach ($originalTokens as $token)
        {
            if (is_array($token) && in_array($token[0], [T_LINE, T_HALT_COMPILER], true)) return $source;
        }
        $source = $this->sortImports($source, $newline);
        $tokens = token_get_all($source, TOKEN_PARSE);
        $parts = array_map(static fn ($token) => is_array($token) ? $token[1] : $token, $tokens);
        $spaces = array_map(static fn ($token) => is_array($token) && $token[0] === T_WHITESPACE, $tokens);
        foreach ($tokens as $index => $token)
        {
            if ($spaces[$index])
            {
                $parts[$index] = preg_replace('/(?:\r?\n)(?:[ \t]*\r?\n){2,}/', $newline . $newline, $parts[$index]);
                if (($tokens[$index - 1] ?? null) === '{' || ($tokens[$index + 1] ?? null) === '}')
                    $parts[$index] = preg_replace('/(?:\r?\n)(?:[ \t]*\r?\n)+/', $newline, $parts[$index]);
            }
            if ($token === ',')
            {
                $next = $index + 1;
                while ($spaces[$next] ?? false) $next++;
                if (in_array($tokens[$next] ?? null, [')', ']'], true)) $parts[$index] = '';
            }
            if ($token !== '{' || !($spaces[$index - 1] ?? false) || str_contains($parts[$index - 1], "\n")) continue;
            $before = implode('', array_slice($parts, 0, $index - 1));
            $line = substr($before, (strrpos($before, "\n") ?: -1) + 1);
            $block = ($tokens[$index - 2] ?? null) === ')';
            for ($cursor = $index - 2; !$block && $cursor >= 0; $cursor--)
            {
                $previous = $tokens[$cursor];
                if (in_array($previous, [';', '{', '}'], true)) break;
                if (is_array($previous) && in_array($previous[0], [T_FUNCTION, T_CLASS, T_INTERFACE, T_TRAIT, T_ENUM, T_ELSE, T_TRY, T_FINALLY], true)) $block = true;
            }
            if (!$block) continue;
            preg_match('/^[ \t]*/', $line, $indent);
            $parts[$index - 1] = $newline . $indent[0];
        }
        $safe = static function ($token): bool
        {
            if (is_array($token))
                return !in_array($token[0], [T_COMMENT, T_DOC_COMMENT, T_INLINE_HTML, T_START_HEREDOC, T_END_HEREDOC], true)
                    && ($token[0] === T_WHITESPACE || !str_contains($token[1], "\n"));
            return $token !== '{' && $token !== '}';
        };
        $comments = array_map(static fn ($token) => is_array($token) && $token[0] === T_COMMENT, $tokens);
        return $this->compact($tokens, $this->uppercaseSections($parts, $spaces, $comments), $spaces, $safe);
    }

    private function sortImports(string $source, string $newline): string
    {
        $tokens = token_get_all($source);
        $offset = 0;
        $depth = 0;
        $imports = [];
        foreach ($tokens as $index => $token)
        {
            $text = is_array($token) ? $token[1] : $token;
            if ($token === '{' || (is_array($token) && in_array($token[0], [T_CURLY_OPEN, T_DOLLAR_OPEN_CURLY_BRACES], true))) $depth++;
            if ($token === '}') $depth--;
            if ($depth === 0 && is_array($token) && $token[0] === T_USE)
            {
                $next = $index + 1;
                while (isset($tokens[$next]) && is_array($tokens[$next]) && $tokens[$next][0] === T_WHITESPACE) $next++;
                if (($tokens[$next] ?? '') !== '(')
                {
                    $declaration = '';
                    $simple = true;
                    for ($cursor = $index; isset($tokens[$cursor]); $cursor++)
                    {
                        $item = $tokens[$cursor];
                        if ((is_array($item) && in_array($item[0], [T_COMMENT, T_DOC_COMMENT], true)) || in_array($item, ['{', '}'], true)) $simple = false;
                        $declaration .= is_array($item) ? $item[1] : $item;
                        if ($item === ';') break;
                    }
                    if ($simple) $imports[] = [$offset, strlen($declaration), $declaration];
                }
            }
            $offset += strlen($text);
        }
        $runs = [];
        foreach ($imports as $import)
        {
            $last = array_key_last($runs);
            if ($last === null)
            {
                $runs[] = [$import];
                continue;
            }
            $previous = $runs[$last][array_key_last($runs[$last])];
            $gap = substr($source, $previous[0] + $previous[1], $import[0] - $previous[0] - $previous[1]);
            if (trim($gap) === '') $runs[$last][] = $import;
            else $runs[] = [$import];
        }
        foreach (array_reverse($runs) as $run)
        {
            $groups = [[], [], []];
            foreach ($run as [, , $declaration])
            {
                $name = preg_replace('/^use\s+(?:(?:function|const)\s+)?/', '', $declaration);
                $group = str_starts_with($name, 'App\\') ? 0 : (str_starts_with($name, 'Framework\\') ? 1 : 2);
                $groups[$group][] = $declaration;
            }
            foreach ($groups as &$group) sort($group, SORT_STRING);
            unset($group);
            $replacement = implode($newline . $newline, array_map(static fn ($group) => implode($newline, $group), array_filter($groups)));
            $first = $run[0];
            $last = $run[array_key_last($run)];
            $source = substr_replace($source, $replacement, $first[0], $last[0] + $last[1] - $first[0]);
        }
        return $source;
    }

    private function phpSignature(string $source): array
    {
        $significant = [];
        foreach (token_get_all($this->sortImports($source, "\n"), TOKEN_PARSE) as $token)
        {
            if (is_array($token) && in_array($token[0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true)) continue;
            $significant[] = is_array($token) ? [$token[0], $token[0] === T_OPEN_TAG ? trim($token[1]) : $token[1]] : $token;
        }
        foreach ($significant as $index => $token)
        {
            if ($token === ',' && in_array($significant[$index + 1] ?? null, [')', ']'], true)) unset($significant[$index]);
        }
        return array_values($significant);
    }

    // =================================================
    // JAVASCRIPT ET CSS
    // =================================================

    private function formatJs(string $source, string $newline): string
    {
        preg_match_all('~\s+|"(?:\\\\.|[^"\\\\])*"|\'(?:\\\\.|[^\'\\\\])*\'|`(?:\\\\.|[^`\\\\])*`|//[^\n]*|/\*[\s\S]*?\*/|/(?:\\\\.|\[(?:\\\\.|[^\]\\\\])*\]|[^/\n\\\\])+/[a-z]*|\{\}|[A-Za-z_$][A-Za-z0-9_$]*|[0-9]+(?:\.[0-9]+)?|.~s', $source, $matches);
        $tokens = $matches[0];
        if (implode('', $tokens) !== $source) throw new RuntimeException('Analyse JavaScript incomplete.');
        $parts = $tokens;
        $spaces = array_map('ctype_space', $tokens);
        foreach ($tokens as $index => $token)
        {
            if ($spaces[$index])
                $parts[$index] = preg_replace('/(?:\r?\n)(?:[ \t]*\r?\n){2,}/', $newline . $newline, $token);
            if ($token === ',')
            {
                $next = $index + 1;
                while ($spaces[$next] ?? false) $next++;
                $previous = $index - 1;
                while ($spaces[$previous] ?? false) $previous--;
                if (in_array($tokens[$next] ?? '', [')', ']', '}'], true) && !in_array($tokens[$previous] ?? '', [',', '['], true)) $parts[$index] = '';
            }
            if ($spaces[$index] && str_contains($token, "\n") && in_array($tokens[$index - 1] ?? '', ['=', ':'], true))
            {
                $before = implode('', array_slice($parts, 0, $index));
                $line = substr($before, (strrpos($before, "\n") ?: -1) + 1);
                $after = implode('', array_slice($parts, $index + 1));
                $nextLine = strtok($after, "\r\n");
                if ($nextLine !== false && strlen($line . ' ' . $nextLine) <= $this->config['line_length'] && !preg_match('~^\s*/[/*]~', $nextLine)) $parts[$index] = ' ';
            }
            if ($token !== '{' || !($spaces[$index - 1] ?? false) || str_contains($parts[$index - 1], "\n")) continue;
            if (!in_array($tokens[$index - 2] ?? '', [')', 'else', 'try', 'finally', '>'], true)) continue;
            $before = implode('', array_slice($parts, 0, $index - 1));
            $line = substr($before, (strrpos($before, "\n") ?: -1) + 1);
            preg_match('/^[ \t]*/', $line, $indent);
            $parts[$index - 1] = $newline . $indent[0];
        }
        $safe = static fn ($token): bool => !in_array($token, ['{', '}'], true)
            && !str_starts_with($token, '//') && !str_starts_with($token, '/*')
            && (ctype_space($token) || !str_contains($token, "\n"));
        $comments = array_map(static fn ($token) => str_starts_with($token, '//'), $tokens);
        $parts = $this->uppercaseSections($parts, $spaces, $comments);
        foreach ($tokens as $index => $token)
        {
            if ($token !== 'import') continue;
            $start = $index + 1;
            while ($spaces[$start] ?? false) $start++;
            if (($tokens[$start] ?? '') !== '{') continue;
            $end = $start + 1;
            while (isset($tokens[$end]) && $tokens[$end] !== '}') $end++;
            if (!isset($tokens[$end])) continue;
            $items = array_slice($parts, $start + 1, $end - $start - 1);
            $names = implode('', $items);
            if (!preg_match('/^[\w\s,$]*$/', $names)) continue;
            $names = trim(preg_replace('/\s+/', ' ', $names));
            $line = '{ ' . $names . ' }';
            $after = implode('', array_slice($parts, $end + 1));
            if (strlen('import ' . $line . preg_split('/\r?\n/', $after, 2)[0]) > $this->config['line_length']) continue;
            $parts[$start] = $line;
            for ($cursor = $start + 1; $cursor <= $end; $cursor++) $parts[$cursor] = '';
        }
        return $this->compact($tokens, $parts, $spaces, $safe);
    }

    private function formatCss(string $source): string
    {
        return preg_replace_callback('/^([ \t]+[-\w]+:)[ \t]*\r?\n((?:[^;{}]|\n)+);/m', function ($match)
        {
            if (str_contains($match[2], '/*') || str_contains($match[2], '"') || str_contains($match[2], "'")) return $match[0];
            $line = $match[1] . ' ' . trim(preg_replace('/\s+/', ' ', $match[2])) . ';';
            return strlen($line) <= $this->config['line_length'] ? $line : $match[0];
        }, $source);
    }

    // =================================================
    // COMPACTAGE ET VALIDATION
    // =================================================

    private function compact(array $tokens, array $parts, array $spaces, callable $safe): string
    {
        $stack = [];
        foreach ($tokens as $index => $token)
        {
            if ($token === '(' || $token === '[') $stack[] = [$index, $token];
            if (!in_array($token, [')', ']'], true) || $stack === []) continue;
            [$start, $opening] = array_pop($stack);
            if (($opening === '(' && $token !== ')') || ($opening === '[' && $token !== ']')) continue;
            $candidateParts = [];
            $allowed = true;
            for ($cursor = $start; $cursor <= $index; $cursor++)
            {
                if (!$safe($tokens[$cursor])) $allowed = false;
                $candidateParts[$cursor] = $spaces[$cursor] ? ' ' : $parts[$cursor];
            }
            if (!$allowed) continue;
            if ($spaces[$start + 1] ?? false) $candidateParts[$start + 1] = '';
            if ($spaces[$index - 1] ?? false) $candidateParts[$index - 1] = '';
            $before = implode('', array_slice($parts, 0, $start));
            $prefix = substr($before, (strrpos($before, "\n") ?: -1) + 1);
            $after = implode('', array_slice($parts, $index + 1));
            $suffix = preg_split('/\r?\n/', $after, 2)[0];
            if (strlen($prefix . implode('', $candidateParts) . $suffix) > $this->config['line_length']) continue;
            foreach ($candidateParts as $cursor => $part) $parts[$cursor] = $part;
        }
        return implode('', $parts);
    }

    private function compile(string $source, string $loader): string
    {
        $binary = JavaScriptBuilder::binary($this->root);
        if (!is_file($binary)) throw new RuntimeException('esbuild requis pour valider JS/CSS : composer js:install');
        $temporary = [];
        $process = null;
        try
        {
            foreach (['input', 'output', 'errors'] as $name)
            {
                $path = tempnam(sys_get_temp_dir(), 'lolissr-dx-');
                if ($path === false) throw new RuntimeException('Fichier temporaire DX indisponible.');
                $temporary[$name] = $path;
            }
            if (file_put_contents($temporary['input'], $source) !== strlen($source))
                throw new RuntimeException('Ecriture temporaire DX incomplete.');
            $process = proc_open(
                [$binary, '--loader=' . $loader, '--minify', '--log-level=error'],
                [0 => ['file', $temporary['input'], 'r'], 1 => ['file', $temporary['output'], 'w'], 2 => ['file', $temporary['errors'], 'w']],
                $pipes, $this->root, null, ['bypass_shell' => true]
            );
            if (!is_resource($process)) throw new RuntimeException('Impossible de lancer esbuild.');
            $status = proc_close($process);
            $process = null;
            if ($status !== 0) throw new RuntimeException('Validation esbuild : ' . file_get_contents($temporary['errors']));
            $result = file_get_contents($temporary['output']);
            if ($result === false) throw new RuntimeException('Resultat esbuild indisponible.');
            return $result;
        }
        finally
        {
            if (is_resource($process)) proc_close($process);
            foreach ($temporary as $path) if (is_file($path)) unlink($path);
        }
    }

    private function uppercaseSections(array $parts, array $spaces, array $comments): array
    {
        foreach ($parts as $index => $part)
        {
            if (!($comments[$index] ?? false) || !preg_match('~^//\s+\S~', $part)) continue;
            $previous = $index - 1;
            while ($spaces[$previous] ?? false) $previous--;
            $next = $index + 1;
            while ($spaces[$next] ?? false) $next++;
            if (($comments[$previous] ?? false) && ($comments[$next] ?? false)
                && preg_match('~^//\s*[-=]{3,}\s*$~', $parts[$previous])
                && preg_match('~^//\s*[-=]{3,}\s*$~', $parts[$next]))
                $parts[$index] = mb_strtoupper($part, 'UTF-8');
        }
        return $parts;
    }
}
